ROLE_TEACHER = "USER_TEACHER"
ROLE_METHODIST = "USER_METHODIST"

ROLE_LABELS = {
    ROLE_TEACHER: "Teacher",
    ROLE_METHODIST: "Methodist",
}


STATUS_DRAFT_EDITING = "DRAFT_EDITING"
STATUS_SUBMITTED_FOR_REVIEW = "DRAFT_SUBMITTED_FOR_REVIEW"
STATUS_FEEDBACK_GIVEN = "DRAFT_FEEDBACK_GIVEN"
STATUS_RESUBMITTED_FOR_REVIEW = "DRAFT_RESUBMITTED_FOR_REVIEW"
STATUS_RPD_VALIDATED = "RPD_VALIDATED"

STATUS_LABELS = {
    STATUS_DRAFT_EDITING: "Editing",
    STATUS_SUBMITTED_FOR_REVIEW: "Submitted for review",
    STATUS_FEEDBACK_GIVEN: "Feedback given",
    STATUS_RESUBMITTED_FOR_REVIEW: "Resubmitted for review",
    STATUS_RPD_VALIDATED: "Validated",
}

REVIEWABLE_STATUSES = [
    STATUS_SUBMITTED_FOR_REVIEW,
    STATUS_RESUBMITTED_FOR_REVIEW,
]

TEACHER_EDITABLE_STATUSES = [
    STATUS_DRAFT_EDITING,
    STATUS_FEEDBACK_GIVEN,
]